name: fitlife
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  liquid_progress_indicator_v2: ^0.5.0  
  google_fonts: ^6.2.1
  simple_animation_progress_bar: ^1.8.2  
  intl: ^0.19.0
  pedometer: ^4.0.2
  permission_handler: ^11.3.1
  get: ^4.6.6
  video_player: ^2.9.2
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  font_awesome_flutter: ^10.8.0
  timeline_tile: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fl_chart: ^0.69.0

flutter:
  uses-material-design: true
  assets:
      - assets/video/push_up.mp4
      - assets/video/squats.mp4
      - assets/video/lunges.mp4
      - assets/video/bicep_curl.mp4
      - assets/video/tricep.mp4
      - assets/video/mountain_climbers.mp4


      - assets/workout/skipping.png
      - assets/workout/fullBody-navs.png
      - assets/workout/warm-up.png
      - assets/workout/burpees.png
      - assets/workout/mountainClimber.png
      - assets/workout/bicycleCrunches.png
      - assets/workout/plank.png
      - assets/workout/skipping_workout.png
      - assets/workout/squats.png
      - assets/workout/lunges.png
      - assets/workout/pushup.png
      - assets/workout/stepups.png
      - assets/workout/gluteBridges.png
      - assets/workout/wallSit.png
      - assets/workout/jumpSquates.png
      - assets/workout/sideLunges.png
      - assets/workout/calfRaises.png
      - assets/workout/planlToPushUp.png
      - assets/workout/renegadeRows.png
      - assets/workout/shoulderPress.png
      - assets/workout/tricepDips.png
      - assets/workout/bicepCurl.png
      - assets/workout/latePullDown.png
      - assets/workout/chestPullDown.png
     
      - assets/workout/fullbody.svg
      - assets/workout/finishWorkout.svg
      


      - assets/icon/Icon-Next.png
      - assets/icon/correct.svg
      - assets/icon/Button-Next.svg
      - assets/icon/meal.png
      - assets/icon/walk.png

      - assets/icon/calories.svg
      - assets/icon/Fat-Icon.svg
      - assets/icon/protein1.svg
      - assets/icon/Carbo-Icon.svg
      

      - assets/icon/home.svg
      - assets/icon/activity.svg
      - assets/icon/profile.svg
      - assets/icon/next-btn.svg
      - assets/icon/dinner.svg
      - assets/icon/fire.svg
      - assets/icon/bell.svg
      - assets/icon/email.svg
      - assets/icon/Lock.svg
      - assets/icon/Login.svg
      - assets/icon/bell-home.svg
      - assets/icon/gender.svg
      - assets/icon/weight.svg
      - assets/icon/height.svg
      - assets/icon/Calendar.svg

      - assets/meal/meal1.svg
      - assets/meal/meal2.svg
      - assets/meal/egg.png
      - assets/meal/broccoli.png
      - assets/meal/apple.png
      - assets/meal/oats.png
      - assets/meal/yogurt.png
      - assets/meal/banana.png
      - assets/meal/almonds.png
      - assets/meal/avocado.png
      - assets/meal/rice.png
      - assets/meal/mixSalad.png
      - assets/meal/tofu.png
      - assets/meal/sweetPatato.png
      - assets/meal/breakfast.png
      - assets/meal/lunch.png
      - assets/meal/dinner.png
    
      - assets/meal/salad.svg
      - assets/meal/pancakes.svg
      - assets/meal/pancake1.svg

      - assets/authentication/loginScr.svg
      - assets/authentication/profileIcon.jpg
      - assets/authentication/logo.png
     
      - assets/bottomsheet/cup.png
      - assets/bottomsheet/glass.png
      - assets/bottomsheet/smallBottle.png
      - assets/bottomsheet/bottle.png
      - assets/bottomsheet/group.png


  
    