name: fitlife
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  liquid_progress_indicator_v2: ^0.5.0  
  
  google_fonts: ^6.2.1
  simple_animation_progress_bar: ^1.8.2  
  intl: ^0.19.0
  pedometer: ^4.0.2
  permission_handler: ^11.3.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fl_chart: ^0.69.0

flutter:
  uses-material-design: true
  assets:
      - assets/workout/skipping.png
      - assets/workout/fullBody-navs.png
      - assets/workout/warm-up.png
     
      - assets/workout/fullbody.svg
      - assets/workout/finishWorkout.svg
      


      - assets/icon/Icon-Next.png
      - assets/icon/correct.svg
      - assets/icon/Button-Next.svg
      - assets/icon/meal.png
      - assets/icon/walk.png

      - assets/icon/calories.svg
      - assets/icon/Fat-Icon.svg
      - assets/icon/protein1.svg
      - assets/icon/Carbo-Icon.svg
      

      - assets/icon/home.svg
      - assets/icon/activity.svg
      - assets/icon/profile.svg
      - assets/icon/next-btn.svg
      - assets/icon/dinner.svg
      - assets/icon/fire.svg
      - assets/icon/bell.svg
      - assets/icon/email.svg
      - assets/icon/Lock.svg
      - assets/icon/Login.svg
      - assets/icon/bell-home.svg
      - assets/icon/gender.svg
      - assets/icon/weight.svg
      - assets/icon/height.svg

      - assets/meal/meal1.svg
      - assets/meal/meal2.svg
      - assets/meal/egg.png
    
      - assets/meal/salad.svg
      - assets/meal/pancakes.svg
      - assets/meal/pancake1.svg

      - assets/authentication/loginScr.svg
      - assets/authentication/profileIcon.jpg
     
      - assets/bottomsheet/cup.png
      - assets/bottomsheet/glass.png
      - assets/bottomsheet/bottle.png

  
    